name: Continious Integration
on:
  push:
    branches:
      - master
      - jenk
  workflow_dispatch:

jobs:
  my_first_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Show Java version
        run: 'java -version'

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: jenk

      - name: Show directory
        run: 'pwd'

      - name: List files
        run: 'ls -al'

      - name: Install Dependencies
        run: 'mvn complile'

      - name: Build application
        run: 'mvn package -DskipTests'

      - name: Test application
        run: 'mvn test'
